### ISSUE TITLE
Migration support: "v2" to "v3" (February 2023)

### ISSUE THREAD

**Issue by andreibancioiu** [multiversx/mx-sdk-js-wallet#34]
[v3](https://github.com/multiversx/mx-sdk-js-wallet/releases/tag/v3.0.0) allows one to store not only password-encrypted secretKeys in the keystores (JSON files), but also password-encrypted mnemonics.

API **breaking changes**:
 - `UserWallet` constructor is now private. It has been replaced by two named constructors (static functions): 
   - `static fromSecretKey({ secretKey, password, })`, where `secretKey` is a `UserSecretKey` object
   - `static fromMnemonic({ mnemonic, password }`, where `mnemonic` is a string

In addition to the existing `decryptSecretKey`, we've now added `decryptMnemonic`.

Changes in keystore's structure:
 - add an extra field: `kind` (payload kind = secret key or mnemonic or arbitrary data).

**Keystore version remained v4.**

Newly generated regular keystore files with encrypted secret keys look as follows:

```
{
    "version": 4,
    "kind": "secretKey",
    ...
}
```

While keystore files with encrypted mnemonics look as follows:

```

{
    "version": 4,
    "kind": "mnemonic",
    ...
}
```

**Full Changelog**: https://github.com/multiversx/mx-sdk-js-wallet/compare/v2.1.3...v3.0.0

**Comment by popenta** [comment]
`sdk-wallet v4` is out now so this issue can be closed.
