### ISSUE TITLE
UserSinger.sign accepts Buffer instead if ISignable - How to sign a transaction now?

### ISSUE THREAD

**Issue by icegriffinguru** [multiversx/mx-sdk-js-wallet#35]
```
const tx = new Transaction({...});
await signer.sign(tx);
const txHash = await networkProvider.sendTransaction(tx);
```
This was the old approach but it's not working anymore because UserSinger.sign accepts Buffer object now.
How to sign a transaction with mx-sdk-wallet v4?

**Comment by andreibancioiu** [comment]
Hello!

Please follow the migration notes here:

https://github.com/multiversx/mx-sdk-js-wallet/issues/33
